---
# tasks file for glusterfs-client-ansible-role

- name: Install glusterfs client
  include: install-glusterfs-client.yml
  when: ansible_distribution == 'CentOS'

- name: Install glusterfs client UBUNTU
  include: install-glusterfs-client.yml
  when: ansible_distribution == 'Ubuntu'

- name: Mount volume(s)
  include: mount-volumes.yml
  when: glusterfs_volumes

- name: Unmount volume(s)
  include: unmount-volumes.yml
  when: glusterfs_volumes
